spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-quartz?useSSL=false&serverTimezone=Asia/Shanghai
    # url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8
    # url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=CTT #这个貌似有问题啊！
    # url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update # update none create
    show-sql: true
    # 实测有效！！ 202106181110
    properties:
      hibernate:
        format_sql: true
  # 使用持久化
  quartz:
    job-store-type: jdbc
    # 这个配置太意外了！！！
    jdbc:
      initialize-schema: always