
package liuyang.testquartz.modules.service.ws.stub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-06-02T15:42:14.368+08:00
 * Generated source version: 3.4.3
 *
 */
public final class HelloInterface_HelloServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.server.modules.testcxf.liuyang/", "HelloServiceService");

    private HelloInterface_HelloServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HelloServiceService ss = new HelloServiceService(wsdlURL, SERVICE_NAME);
        HelloInterface port = ss.getHelloServicePort();

        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_arg0 = "";
        int _sayHello_arg1 = 0;
        java.lang.String _sayHello__return = port.sayHello(_sayHello_arg0, _sayHello_arg1);
        System.out.println("sayHello.result=" + _sayHello__return);


        }

        System.exit(0);
    }

}
